### ISSUE TITLE
LED going off without command

### ISSUE THREAD

**Issue by ajcooper72** [ThePiHut/statusboard-statuszero-docs#5]
Having issue with the lights going off after random amount of time, and then not responding to any further commands.  Here's some sample code.  Green light for row one is illuminated then at some point between 10 and 60 seconds it goes off for no apparent reason.  

```python
#!/usr/bin/env python

from gpiozero import StatusBoard
from time import sleep

sb = StatusBoard()


while True:
    sb.one.lights.green.on()
    print(sb)
    sleep(2)
```

Not sure why this is happening.  Doesn't seem to matter what light I test.

**Comment by bennuttall** [comment]
Did this problem persist?

**Comment by ajcooper72** [comment]
I'm using the status board with Home Assistant now, and not experiencing any issues.
